packages:
  - apps/*
  - packages/*
  - tooling/*

catalogs:
  react:
    react: ^19.2.0
    react-dom: ^19.2.0
    "@types/react": ^19.2.0
    "@types/react-dom": ^19.2.0
    babel-plugin-react-compiler: ^1.0.0

  convex:
    convex: ^1.25.2
    convex-helpers: ^0.1.104
    "@convex-dev/rate-limiter": ^0.2.10

  common:
    lucide-react: ^0.545.0
    zod: ^4.1.3

  prettier:
    "@ianvs/prettier-plugin-sort-imports": ^4.7.0
    prettier: ^3.6.2
    prettier-plugin-tailwindcss: ^0.6.14

  eslint:
    eslint: ^9.37.0

  typescript:
    typescript: ^5.8.3

  tanstack:
    "@tanstack/react-query": ^5.90.2
    "@tanstack/react-router": ^1.132.37
    "@tanstack/react-query-devtools": ^5.90.2
    "@tanstack/react-router-devtools": ^1.132.37
    "@tanstack/react-form": ^1.23.5
