packages:
  - apps/*
  - packages/*
  - tooling/*

catalogs:
  react:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@types/react": ^19.1.8
    "@types/react-dom": ^19.1.6

  common:
    zod: ^4.0.17

  prettier:
    "@ianvs/prettier-plugin-sort-imports": ^4.4.2
    prettier: ^3.5.3
    prettier-plugin-tailwindcss: ^0.6.11

  eslint:
    eslint: ^9.28.0

  typescript:
    typescript: ^5.8.3
