packages:
  - apps/spa-web
  - packages/*
  - tooling/*

catalogs:
  react:
    react: ^19.2.0
    react-dom: ^19.2.0
    "@types/react": ^19.2.0
    "@types/react-dom": ^19.2.0

  convex:
    convex: ^1.25.2
    convex-helpers: ^0.1.104
    "@convex-dev/rate-limiter": ^0.2.10

  common:
    zod: ^4.1.3

  prettier:
    "@ianvs/prettier-plugin-sort-imports": ^4.7.0
    prettier: ^3.6.2
    prettier-plugin-tailwindcss: ^0.6.14

  eslint:
    eslint: ^9.28.0

  typescript:
    typescript: ^5.8.3
