/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125ProtectedRouteRouteImport } from './routes/{-$locale}/_protected/route'
import { Route as Char123LocaleChar125ProtectedTaskTypesRouteImport } from './routes/{-$locale}/_protected/task-types'
import { Route as Char123LocaleChar125ProtectedDashboardRouteImport } from './routes/{-$locale}/_protected/dashboard'

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ProtectedRouteRoute =
  Char123LocaleChar125ProtectedRouteRouteImport.update({
    id: '/_protected',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ProtectedTaskTypesRoute =
  Char123LocaleChar125ProtectedTaskTypesRouteImport.update({
    id: '/task-types',
    path: '/task-types',
    getParentRoute: () => Char123LocaleChar125ProtectedRouteRoute,
  } as any)
const Char123LocaleChar125ProtectedDashboardRoute =
  Char123LocaleChar125ProtectedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => Char123LocaleChar125ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125ProtectedRouteRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125ProtectedDashboardRoute
  '/{-$locale}/task-types': typeof Char123LocaleChar125ProtectedTaskTypesRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125ProtectedDashboardRoute
  '/{-$locale}/task-types': typeof Char123LocaleChar125ProtectedTaskTypesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/_protected': typeof Char123LocaleChar125ProtectedRouteRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/_protected/dashboard': typeof Char123LocaleChar125ProtectedDashboardRoute
  '/{-$locale}/_protected/task-types': typeof Char123LocaleChar125ProtectedTaskTypesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/task-types'
  fileRoutesByTo: FileRoutesByTo
  to: '/{-$locale}' | '/{-$locale}/dashboard' | '/{-$locale}/task-types'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/_protected'
    | '/{-$locale}/'
    | '/{-$locale}/_protected/dashboard'
    | '/{-$locale}/_protected/task-types'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_protected': {
      id: '/{-$locale}/_protected'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125ProtectedRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_protected/task-types': {
      id: '/{-$locale}/_protected/task-types'
      path: '/task-types'
      fullPath: '/{-$locale}/task-types'
      preLoaderRoute: typeof Char123LocaleChar125ProtectedTaskTypesRouteImport
      parentRoute: typeof Char123LocaleChar125ProtectedRouteRoute
    }
    '/{-$locale}/_protected/dashboard': {
      id: '/{-$locale}/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/{-$locale}/dashboard'
      preLoaderRoute: typeof Char123LocaleChar125ProtectedDashboardRouteImport
      parentRoute: typeof Char123LocaleChar125ProtectedRouteRoute
    }
  }
}

interface Char123LocaleChar125ProtectedRouteRouteChildren {
  Char123LocaleChar125ProtectedDashboardRoute: typeof Char123LocaleChar125ProtectedDashboardRoute
  Char123LocaleChar125ProtectedTaskTypesRoute: typeof Char123LocaleChar125ProtectedTaskTypesRoute
}

const Char123LocaleChar125ProtectedRouteRouteChildren: Char123LocaleChar125ProtectedRouteRouteChildren =
  {
    Char123LocaleChar125ProtectedDashboardRoute:
      Char123LocaleChar125ProtectedDashboardRoute,
    Char123LocaleChar125ProtectedTaskTypesRoute:
      Char123LocaleChar125ProtectedTaskTypesRoute,
  }

const Char123LocaleChar125ProtectedRouteRouteWithChildren =
  Char123LocaleChar125ProtectedRouteRoute._addFileChildren(
    Char123LocaleChar125ProtectedRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125ProtectedRouteRoute: typeof Char123LocaleChar125ProtectedRouteRouteWithChildren
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125ProtectedRouteRoute:
      Char123LocaleChar125ProtectedRouteRouteWithChildren,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
